import { useState } from 'react'
import Head from 'next/head'
import Image from 'next/image'

import QuickWrapper from '@/components/Layout/QuickWrapper'
import Quick from '@/components/Quick'

import Lightning from '@assets/icons/lightning.svg'
import Chats from '@assets/icons/chats.svg'
import TodoList from '@assets/icons/todo-lists.svg'
import Search from '@assets/icons/search.svg'
import Loading from '@assets/icons/loading.svg'

const Home = () => {
  const [isExpand, setIsExpand] = useState(false)

  const toggleExpand = () => {
    setIsExpand(!isExpand)
  }

  return (
    <>
      <Head>
        <title>Quicks Project</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <QuickWrapper>
          <div className="flex flex-col bg-white rounded-md py-5 px-8 w-[500px] h-[500px]">
            <div className="relative w-full">
              <input type="text" className="border border-primary-3 rounded-md w-full px-5 py-1 text-sm placeholder:text-black" placeholder="Search" />
              <Image
                className="absolute right-5 top-2.5"
                src={Search}
                alt="search-icon"
                quality={100}
                priority
              />
            </div>
            <div className="flex flex-1 justify-center items-center">
              <div className="flex flex-col items-center gap-3">
                <Image
                  className="animate-spin"
                  src={Loading}
                  alt="loading-icon"
                  quality={100}
                  priority
                />
                <strong className="text-primary-2">Loading Chats...</strong>
              </div>
            </div>
          </div>
          <div className="flex flex-row justify-end gap-4">
            <Quick className={`transition-all duration-700 ${isExpand && 'translate-x-10 absolute bottom-0 right-10 invisible'}`} src={TodoList} variant="default" label={`${!isExpand ? 'Task' : ''}`} />
            <Quick className={`transition-all duration-700 ${isExpand && 'translate-x-10 absolute bottom-0 right-10 invisible'}`} src={Chats} variant="default" label={`${!isExpand ? 'Inbox' : ''}`} />
            <Quick src={Lightning} onClick={toggleExpand} />
          </div>
        </QuickWrapper>
      </main>
    </>
  )
}

export default Home;
